src/Entity/Announcement.php
<?php

namespace App\Entity;


use App\Repository\AnnouncementRepository;
use App\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;


/**
 * @ORM\Entity(repositoryClass=AnnouncementRepository::class)

 */
class Announcement
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"announcementFav:read"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"announcementFav:read"})
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Groups({"announcementFav:read"})
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"announcementFav:read"})
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Groups({"announcementFav:read"})
     */
    private $updated_at;

    /**
     * @ORM\ManyToMany(targetEntity=SocialNetwork::class, inversedBy="announcements")
     */
    private $socialNetworks;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="announcements")
     * @Groups({"announcementFav:read"})
     */
    private $categories;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="announcements")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=AnnouncementFav::class, mappedBy="announcement", orphanRemoval=true)
     */
    private $favorites;

    /**
     * @ORM\OneToMany(targetEntity=AnnouncementReport::class, mappedBy="announcement", orphanRemoval=true)
     */
    private $reports;


    

    public function __construct()
    {
        $this->socialNetworks = new ArrayCollection();
        $this->categories = new ArrayCollection();
        $this->created_at = new \DateTime;
        $this->status = true; // true = active

        $this->favorites = new ArrayCollection();
        $this->reports = new ArrayCollection();       
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    public function getImageWithPath()
    {
        //Set path for easyadmin
        return 'assets/images/image_announcement/'.$this->image;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|SocialNetwork[]
     */
    public function getSocialNetworks(): Collection
    {
        return $this->socialNetworks;
    }

    public function addSocialNetwork(SocialNetwork $socialNetwork): self
    {
        if (!$this->socialNetworks->contains($socialNetwork)) {
            $this->socialNetworks[] = $socialNetwork;
        }

        return $this;
    }

    public function removeSocialNetwork(SocialNetwork $socialNetwork): self
    {
        if ($this->socialNetworks->contains($socialNetwork)) {
            $this->socialNetworks->removeElement($socialNetwork);
        }

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|AnnouncementFav[]
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(AnnouncementFav $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites[] = $favorite;
            $favorite->setAnnouncement($this);
        }

        return $this;
    }

    public function removeFavorite(AnnouncementFav $favorite): self
    {
        if ($this->favorites->contains($favorite)) {
            $this->favorites->removeElement($favorite);
            // set the owning side to null (unless already changed)
            if ($favorite->getAnnouncement() === $this) {
                $favorite->setAnnouncement(null);
            }
        }

        return $this;
    }

    //function for check if an announcement is in the user's favorites
    public function isFavByUser(User $user) : bool
    {
        foreach($this->favorites as $favorite){
            if ($favorite->getUser() === $user) return true;
        }

        return false;
    }

    /**
     * @return Collection|AnnouncementReport[]
     */
    public function getReports(): Collection
    {
        return $this->reports;
    }

    public function addReport(AnnouncementReport $report): self
    {
        if (!$this->reports->contains($report)) {
            $this->reports[] = $report;
            $report->setAnnouncement($this);
        }

        return $this;
    }

    public function removeReport(AnnouncementReport $report): self
    {
        if ($this->reports->contains($report)) {
            $this->reports->removeElement($report);
            // set the owning side to null (unless already changed)
            if ($report->getAnnouncement() === $this) {
                $report->setAnnouncement(null);
            }
        }

        return $this;
    }

    //function to check if an announcement was reported by this user
    public function isReportedByUser(User $user) : bool
    {
        foreach($this->reports as $report){
            if ($report->getReporter() === $user) return true;
        }

        return false;
    }

   
}

src/Controller/AnnouncementController.php
<?php

namespace App\Controller;

use App\Entity\Announcement;
use App\Entity\AnnouncementFav;
use App\Entity\AnnouncementReport;
use App\Entity\User;
use App\Form\AnnouncementType;
use App\Repository\AnnouncementFavRepository;
use App\Repository\AnnouncementReportRepository;
use App\Repository\AnnouncementRepository;
use App\Repository\CategoryRepository;
use App\Repository\SocialNetworkRepository;
use App\Service\ImageUploader;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Length;

/**
 * @Route("/annonce", name="announcement_")
 */
class AnnouncementController extends AbstractController
{
    /**
     * @Route("/liste", name="list", methods={"GET"})
     */
    public function list(AnnouncementRepository $announcementRepository, CategoryRepository $categoryRepository, SocialNetworkRepository $socialNetworkRepository, Request $request): Response
    {
        $announcements = $announcementRepository->findAll();

        // If search is done, we try to find a match by title, then if no match, find by content
        $search = $request->query->get("search", null);
        if ($search) {
            $announcements = $announcementRepository->searchByTitle($search);
            if (!$announcements) {
                $announcements = $announcementRepository->searchByContent($search);
            }
        }

        $categories = $categoryRepository->findAll();
        $socialNetworks = $socialNetworkRepository->findAll();
        return $this->render('announcement/list.html.twig', [
            'announcements' => $announcements, 'categories' => $categories, 'socialNetworks' => $socialNetworks
        ]);
    }

    /**
     * @Route("/new", name="new", methods={"GET","POST"})
     */
    public function new(Request $request, ImageUploader $imageUploader): Response
    {

        $announcement = new Announcement();
        $form = $this->createForm(AnnouncementType::class, $announcement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // If an image is uploaded, Image Uploader service is called to create a random unique file name and move image to the right folder
            $imageName = $imageUploader->moveFile($form->get('pictureFile')->getData(), "image_announcement");
            if ($imageName) {
                $announcement->setImage($imageName);
            };

            $announcement->setUser($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($announcement);
            $entityManager->flush();

            return $this->redirectToRoute('user_dashboard', ['id' => $this->getUser()->getId()]);
        }

        return $this->render('announcement/new.html.twig', [
            'announcement' => $announcement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="show", methods={"GET", "POST"})
     */
    public function show(Announcement $announcement, CategoryRepository $catRepo, Request $request, MailerInterface $mailer): Response
    {

        $similarAnnouncements = $catRepo->findAnnouncementByCategory($announcement);
        $this->denyAccessUnlessGranted('show', $announcement);

        // Contact form handling
        $senderMessage = $request->request->get('txtMsg');
        if ($senderMessage) {

            $email = (new Email())
            ->from($request->request->get('txtEmail'))
            ->to($announcement->getUser()->getEmail())
            ->subject('O\'Dience - ' . $request->request->get('txtName') . ' veut en savoir plus sur votre annonce !')
            ->html('
                <p><b>Annonce: ' . $announcement->getTitle() . '</b></p>
                <p>' .$senderMessage. '</p>
            
            ');
            $mailer->send($email);
        }



        return $this->render('announcement/show.html.twig', [
            'similarAnnouncements'=> $similarAnnouncements,
            'announcement' => $announcement
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Announcement $announcement, ImageUploader $imageUploader): Response
    {

        $this->denyAccessUnlessGranted('edit', $announcement);

        $form = $this->createForm(AnnouncementType::class, $announcement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // If an image is uploaded, Image Uploader service is called to create a random unique file name and move image to the right folder
            $imageName = $imageUploader->moveFile($form->get('pictureFile')->getData(), "image_announcement");
            if ($imageName) {
                $announcement->setImage($imageName);
            };
            $announcement->setUpdatedAt(new \DateTime());
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('announcement_show', ['id' => $announcement->getId()]);
        }

        return $this->render('announcement/edit.html.twig', [
            'announcement' => $announcement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="delete", methods={"DELETE"})
     */
    public function delete(Request $request, Announcement $announcement): Response
    {
        $this->denyAccessUnlessGranted('delete', $announcement);

        if ($this->isCsrfTokenValid('delete' . $announcement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($announcement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_dashboard', ['id'=> $this->getUser()->getId()]);
    }

    /**
     * 
     * add or remove an announcement to the favorites
     * 
     * @Route("/{id}/favoris", name="favorite")
     *
     * @param Announcement $announcement
     * @param ObjectManager $manager
     * @param AnnouncementFavRepository $favRepo
     * @return Response
     */
    public function favorites(Announcement $announcement, EntityManagerInterface $manager, AnnouncementFavRepository $favRepo): Response
    {
        $user =$this->getUser();

        if(!$user){

        return $this->json(['code'=>403, 'message'=>'Unauthorizer'], 403);

        }
        if ($announcement->isFavByUser($user)){
            $favorite = $favRepo->findOneBy([
                'announcement'=>$announcement,
                'user'=>$user
            ]);
            
            $manager->remove($favorite);
            $manager->flush();

            return $this->json(['code'=>200, 'message'=> 'L\'annonce '.  $announcement->getTitle() . ' a été retirée de vos favoris !'], 200);
        }

        $favorite = new AnnouncementFav();
        $favorite->setAnnouncement($announcement);
        $favorite->setUser($user);

        $manager->persist($favorite);
        $manager->flush();
        return $this->json(['code'=>200, 'message'=> 'L\'annonce '.  $announcement->getTitle() . ' a été ajoutée à vos favoris !'], 200);
    }

    /**
     * Report an announcement
     * 
     * @Route("/{id}/signaler", name="report")
     * 
     * @param Announcement $announcement
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function report(Announcement $announcement, EntityManagerInterface $manager): Response
    {
        $user = $this->getUser();

        if (!$user) {
            return $this->json(['code' => 403, 'message' => 'Unauthorized'], 403);
        }

        if ($announcement->isReportedByUser($user)) {
            return $this->json(['code' => 200, 'message '=> 'Vous avez déjà signalé cette annonce !'], 200);
        }

        $report = new AnnouncementReport();
        $report->setAnnouncement($announcement);
        $report->setReporter($user);

        $manager->persist($report);
        $manager->flush();
        return $this->json(['code' => 200, 'message' => 'L\'annonce '. $announcement->getTitle() . ' a été signalée par ' . $user->getUsername() . '.'], 200);
    }
}

templates/announcement/_delete_form.html.twig
<form method="post" action="{{ path('announcement_delete', {'id': announcement.id}) }}" onsubmit="return confirm('Souhaitez-vous vraiment supprimer cette annonce?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ announcement.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/announcement/_edit_form.html.twig
<div class="container-md mt-5">
	<div class="row profile align-items-center">
		
		<div class="card bg-light col-md-12">
		<article class="card-body">
		<h4 class="card-title mt-3 text-center mb-5">Modifier l'annonce </h4>
		{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}	
		<div class="form-row">
			<div class="form-group col-md-6">
				<label>Titre</label>
				{{form_widget(form.title)}}
			</div>
             <div class="form-group col-md-6">
				<label>Image<em>(optionnel)</em></label>
				{{form_widget(form.pictureFile)}}	
			</div>
        </div>
        
        <div class="form-row">
            <div class="form-group col-md-12">
				<label>Détail</label>
				{{form_widget(form.content)}}	
			</div>
        </div>     

        <div class="form-row">
			<div class="form-group col-md-6">
				<label>Réseaux requis <em>(optionnel)</em></label>
				{{form_widget(form.socialNetworks)}}
			</div>
             <div class="form-group col-md-6">
				<label>Catégories</label>
				{{form_widget(form.categories)}}	
			</div>
        </div>

		<div class="d-flex justify-content-between">
            <div class="form-group col-md-4">
                <button type="submit" class="btn btn-primary btn-block"> Valider les modifications </button>
            </div>                                                                
		{{ form_end(form) }}

templates/announcement/_form.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Soumettre l\'annonce') }}</button>
{{ form_end(form) }} #}



<div class="container-md mt-5">
	<div class="row profile align-items-center">
		
		<div class="card bg-light col-md-12">
		<article class="card-body">
		<h4 class="card-title mt-3 text-center">Nouvelle annonce </h4>
		{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}	
		<div class="form-row">
			<div class="form-group col-md-6">
				<label>Titre de l'annonce</label>
				{{form_widget(form.title)}}
			</div>
             <div class="form-group col-md-6">
				<label>Image de l'annonce <em>(optionnel)</em></label>
				{{form_widget(form.pictureFile)}}	
			</div>
        </div>
        
        <div class="form-row">
            <div class="form-group col-md-12">
				<label>Détail de l'annonce</label>
				{{form_widget(form.content)}}	
			</div>
        </div>     

        <div class="form-row">
			<div class="form-group col-md-6">
				<label>Réseaux requis <em>(optionnel)</em></label>
				{{form_widget(form.socialNetworks)}}
			</div>
             <div class="form-group col-md-6">
				<label>Catégories</label>
				{{form_widget(form.categories)}}	
			</div>
        </div>

		<div class="d-flex justify-content-between">
            <div class="form-group col-md-4">
                <button type="submit" class="btn btn-primary btn-block"> Soumettre l'annonce </button>
            </div>   
            <a href="{{ path('homepage') }}" class="mt-2">Retour au tableau de bord</a>
        </div>                                                                    
		{{ form_end(form) }}

templates/announcement/list.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ parent() }} - Liste des annonces{% endblock %}


{% block stylesheets %}
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons">

<link href='{{asset('assets/css/announcement_list.css')}}' rel='stylesheet' type='text/css'>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
{% endblock %}


{% block body %}

<div class="container-fluid list__wrapper">
    <div class="row main__div mt-5">
        <div class="border_announcement w-100 pb-5" >
            <h1 class="text-center text-info h2 mt-5">Liste des annonces</h1>
            {% include 'partials/_filters.html.twig' %}
            <div class="col-lg-11 col-xl-9 mx-lg-auto">
                {% for announcement in announcements %}
                <div class="list-group panel my-2">
                    <div href="#" class="list-group-item d-flex flex-column align-items-center justify-content-center flex-md-row bg-white mb-1 p-3">

                        {# PICTURE #}
                        {% if announcement.image is not empty %} 
                        <div class="media d-flex justify-content-center">
                            <figure class="">
                                <img class="media-object rounded img-fluid"  src="{{asset('/assets/images/avatar_user/') ~ announcement.user.picture}}">
                            </figure>
                        </div>
                        {% elseif announcement.user.picture is not empty %}
                        <div class="media d-flex justify-content-center">
                            <figure class="">
                                <img class="media-object rounded img-fluid"  src="{{asset('/assets/images/avatar_user/') ~ announcement.user.picture}}">
                            </figure>
                        </div>
                        {% endif %}
                        {# /PICTURE #}

                        <div class=" d-flex flex-column align-items-center px-md-5 announcement__content">
                            {# CONTENT #}
                            <div class="">
                                <div class="d-flex flex-column flex-md-row justify-content-between">
                                    <h3 class="h4 text-centertext-md-left">{{announcement.title}}
                                    <em class="user_name">
                                        (<a href="{{path('user_show', {'id' : announcement.user.id})}}">{{announcement.user}}</a>)
                                    </em>        
                                    </h3>
                                    {% if announcement.updatedAt is not empty %}
                                        <p class="font-italic text-black-50 d-flex flex-md-row-reverse text-left text-md-right announcement__date"> Modifié le {{ announcement.updatedAt ? announcement.updatedAt|date('d-m-Y à H:i') : '' }} </p>
                                    {% else %}
                                        <p class="font-italic text-black-50 d-flex flex-md-row-reverse text-left text-md-right announcement__date"> Publiée le {{ announcement.createdAt ? announcement.createdAt|date('d-m-Y à H:i') : '' }}</p>
                                    {% endif %}
                                </div>
                                <p class="d-none d-sm-block">{{ announcement.content | slice (0, 150) }}...</p>
                            </div>
                            {# /CONTENT #}
                            {# CATEGORIES AND SOCIALS #}
                            <div class="d-flex flex-column flex-md-row w-100 justify-content-around align-items-between">
                                <div class="d-flex flex-column">
                                    <small>Catégories</small>
                                    <div class="d-flex">
                                        {% for category in announcement.categories %}
                                        <div class="d-flex flex-column mx-auto">
                                            <div>
                                                <span data-category-id="{{ category.id }}"> </span>
                                            </div>
                                            <div class="mx-auto ">
                                                <img src="{{asset('/assets/images/category_picto/') ~ category.picto}}" class="img_resize mt-2">
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="d-flex flex-column">
                                    <small>Plateformes requises</small>
                                    <div class="d-flex">
                                        {% for network in announcement.socialNetworks %}
                                        <div class=" flex-row mx-auto">
                                            <div class="mx-auto">
                                                <span class="d-none" data-network-id="{{ network.id }}"></span>
                                            </div>
                                            <div class="mx-auto">
                                                <img src="{{asset('/assets/images/social_picto/') ~ network.picto}}" class="img_resize mt-2">
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            {# /CATEGORIES AND SOCIALS #}
                        </div>
                        {# BUTTONS #}
                        <div class=" my-2 my-md-0 d-flex flex-column justify-content-center">
                            <a href="{{path('announcement_favorite', {'id': announcement.id}) }}"  class="link_fav js-fav btn btn-info btn-sm btn-block btn_color w-60 my-1">   
                                {% if app.user and announcement.isFavByUser(app.user) %}
                                <i class="fa fa-heart fa-lg mr-2 "></i> <span class="favtext">Retirer des favoris</span>
                                {% else %}
                                <i class="fa fa-heart-o fa-lg mr-2"></i> <span class="favtext">Ajouter aux favoris</span>
                                {% endif %}
                            </a>
                            <a href="{{ path('announcement_show', {id:announcement.id }) }}" class="btn btn-info btn-sm btn-block btn_color w-60 my-1">
                                <i class="fa fa-eye fa-lg mr-2"></i> 
                                <span class="show_ann">Consulter l'annonce</span>
                            </a>
                        </div>
                        {# /BUTTONS #}
                    </div>
                </div>
                {% endfor %}  
            <div>  
        </div>
	</div>
</div>

{% endblock %}

{% block javascripts %}
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>

    let categoryFilter = '';
    let networkFilter = '';
		    // Filters announcements by category
    function filterByCategory(evt) {
        categoryFilter = evt.target.value;
        updateDisplay();
    }

    // Filters announcements by social network
    function filterByNetwork(evt) {
        networkFilter = evt.target.value;
        updateDisplay();
    }

    // Updates display of announcements according to the filters
    function updateDisplay() {
        document.querySelectorAll('.panel').forEach(function(announcement){
            let foundCategory = false;
            let foundNetwork = false;
            
            if (categoryFilter == '') {
                foundCategory = true;
            }
            else {
                announcement.querySelectorAll('span[data-category-id]').forEach(function(categoryTag){
                    if (categoryTag.dataset.categoryId == categoryFilter) {
                        foundCategory = true;
                    }
                })
            }

            if (networkFilter == '') {
                foundNetwork = true;
            }
            else {
                announcement.querySelectorAll('span[data-network-id]').forEach(function(network){
                    if (network.dataset.networkId == networkFilter) {
                        foundNetwork = true;
                    }
                })
            }
            
            if (foundCategory && foundNetwork) {

							announcement.classList.remove("d-none")
							announcement.nextElementSibling.classList.remove("d-none")
              //announcement.style.display = 'flex';
              //announcement.nextElementSibling.style.display = 'flex';
            }
            else {
							announcement.classList.add("d-none")
							announcement.nextElementSibling.classList.add("d-none")
                // announcement.style.display = 'none';
                // announcement.nextElementSibling.style.display = 'none';
            }
        })
    }

        function onClickBtnFav(evt){
        evt.preventDefault()
        const url = this.href
        const icone = this.querySelector('i');
        let favlink = evt.currentTarget;
        let favtext = this.querySelector('.favtext');
        

        axios.get(url).then(function(response){
            if(icone.classList.contains('fa-heart-o')){
                icone.classList.replace('fa-heart-o', 'fa-heart')
                favtext.innerHTML = "Retirer des favoris";
                
            } else{
                icone.classList.replace('fa-heart', 'fa-heart-o')
                favtext.innerHTML = "Ajouter aux favoris";
                
            }
        });
    }

        document.querySelectorAll('a.js-fav').forEach(function(link){
        link.addEventListener('click', onClickBtnFav)
    })
    document.querySelectorAll('a.js-report').forEach(function(link){
        link.addEventListener('click', onClickBtnReport);
    })

		document.getElementById('category_label').addEventListener('change', filterByCategory);
    document.getElementById('socialNetwork_name').addEventListener('change', filterByNetwork);
		</script>
{% endblock %}

templates/announcement/new.html.twig
{% extends 'layouts/dashboard.html.twig' %}
{% block content %}
		<div class="card bg-light profile-content">
			<article class="card-body">
				<h4 class="card-title mt-3 text-center">Nouvelle annonce</h4>
				{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
				<div class="form-row">
					<div class="form-group col-md-6">
						<label>Titre de l'annonce</label>
						{{form_widget(form.title)}}
					</div>
					<div class="form-group col-md-6">
						<label>Image de l'annonce
							<em>(optionnel)</em>
						</label>
						{{form_widget(form.pictureFile)}}
					</div>
				</div>
				<div class="form-row">
					<div class="form-group col-md-12">
						<label>Détail de l'annonce</label>
						{{form_widget(form.content)}}
					</div>
				</div>
				<div class="form-row">
					<div class="form-group col-md-6">
						<label>Réseaux requis
							<em>(optionnel)</em>
						</label>
						{{form_widget(form.socialNetworks)}}
					</div>
					<div class="form-group col-md-6">
						<label>Catégories</label>
						{{form_widget(form.categories)}}
					</div>
				</div>
				<div class="form-group col-md-4 mx-auto">
					<button type="submit" class="btn btn-primary btn-block">
						Publier l'annonce
					</button>
				</div>
				{{ form_end(form) }}
			</article>
		</div>
{% endblock %}